export const GET_ENTERPRISES = 'GET_ENTERPRISES';
export const GET_DOMAINS = 'GET_DOMAINS';
export const GET_SOLUTIONS = 'GET_SOLUTIONS';
export const GET_BYID = 'GET_BYID';
export const GET_FIELD = 'GET_FIELD';
export const RESPONSE_LOADING = 'RESPONSE_LOADING';